---
sudo: false
language: ruby
cache: bundler

addons:
  chrome: stable

before_install:
  - sudo apt update -qq
  - sudo apt install -y chromium-chromedriver
  - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/
  - gem install bundler -v 2.0.1

rvm:
  - 2.6.2
