language: ruby
cache: bundler

addons:
  chrome: stable

before_install:
  - sudo apt update -qq
  - sudo apt install -y chromium-chromedriver
  - gem install bundler -v 2.0.1

rvm:
  - 2.6.2

env:
  - TEST_FRAMEWORK=test-unit
  - TEST_FRAMEWORK=minitest
  - TEST_FRAMEWORK=rspec
