dist: focal
language: ruby
cache: bundler

addons:
  chrome: stable

before_install:
  - sudo apt update -qq
  - sudo apt install -y chromium-chromedriver

rvm:
  - 2.7.2

env:
  - TEST_FRAMEWORK=test-unit
  - TEST_FRAMEWORK=minitest
  - TEST_FRAMEWORK=rspec
